services:
  - type: web
    name: devi-fancy-store
    runtime: docker
    dockerfilePath: ./php_app/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: devi_fancy_store
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
