services:
  - type: web
    name: devi-fancy-store
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: devi-fancy-store-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: devi-fancy-store-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: devi-fancy-store-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: devi-fancy-store-db
          property: database
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: devi-fancy-store-db
    plan: free
    databaseName: devi_fancy_store
